#!/bin/bash
echo $1
#node -e "console.log($1)"
/usr/local/bin/node -e "const { NitrilePreviewNode } = require ('/Users/james/github/nitrile-preview/lib/nitrile-preview-node'); new NitrilePreviewNode().to_html_document_async('$1').then(([fullname]) => { console.log(fullname); const viewer = require('child_process').spawn('open',[fullname]); }).catch(err => {console.log(err);process.exitCode=1;})"


