#!/bin/bash
#echo $*
#node -e "console.log($*)"
/usr/local/bin/node -e "const { NitrilePreviewServer } = require ('$HOME/github/nitrile-preview/lib/nitrile-preview-server'); new NitrilePreviewServer('$*').run()"


